# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Spring Boot CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test with Gradle
      run: ./gradlew test
    
  build:

    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -x test
    - name: Listing all the files
      run: ls ${{ github.workspace }}
      
    - name: Upload application
      uses: appleboy/scp-action@master
      with:       
        host: ec2-18-159-213-239.eu-central-1.compute.amazonaws.com       
        username: ubuntu      
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        source: "build/libs/generactive-0.0.1-SNAPSHOT.jar"      
        target: "~/source"
        
    - name: Start Service
      uses: appleboy/ssh-action@master
      with:
        host: ec2-18-159-213-239.eu-central-1.compute.amazonaws.com         
        username: ubuntu     
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          sudo /etc/init.d/my-app stop
          mv ~/source/app.jar ~/source/app-old.jar
          mv ~/source/build/libs/generactive-0.0.1-SNAPSHOT.jar ~/source/app.jar
          sudo rm -rf /etc/init.d/my-app
          sudo ln -s -f ~/source/app.jar /etc/init.d/app
          sudo /etc/init.d/app start
          rm ~/source/app-old.jar
      
      
      
  list-all-files:
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
      - name: Listing all the files
        run: ls ${{ github.workspace }}
    
  
